---
title: "Hands-on Exercise 5(2)"
author: "farrahmf"
date: "10 February 2023"
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---

# Correlation Matrices

### Loading packages and importing data

```{r}
pacman::p_load(corrplot, ggstatsplot, tidyverse)
wine <- read_csv("data/wine_quality.csv")
```

### Using *pairs()*

```{r}
pairs(wine[,1:11])
```

```{r}
pairs(wine[,2:12], lower.panel = NULL)
```

Showing the correlation coefficient of each pair of variables:

```{r}
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y, use = "complete.obs"))
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste(prefix, txt, sep = "")
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = cex.cor * (1 + r)/2)
}

pairs(wine[,2:12], upper.panel = panel.cor)
```

### Using *ggcorrmat()*

*Code below won't run, error message:*

Error in titleGrob(label, x, y, hjust = hj, vjust = vj, angle = angle, :

unused argument (expand_y = TRUE)

```{r eval=FALSE, include=FALSE}
ggstatsplot::ggcorrmat(data = wine, 
                       cor.vars = 1:11,
                       ggcorrplot.args = list(outline.color = "black",
                                              hc.order = TRUE,
                                              tl.cex = 10),
                       title = "Correlogram for wine dataset",
                       subtitle = "Four pairs are not significant at p < 0.05")

```

```{r}
grouped_ggcorrmat(
  data = wine,
  cor.vars = 1:11,
  grouping.var = type,
  type = "robust",
  p.adjust.method = "holm",
  plotgrid.args = list(ncol = 2),
  ggcorrplot.args = list(outline.color = "black", 
                         hc.order = TRUE,
                         tl.cex = 10),
  annotation.args = list(
    tag_levels = "a",
    title = "Correlogram for wine dataset",
    subtitle = "The measures are: alcohol, sulphates, fixed acidity, citric acid, chlorides, residual sugar, density, free sulfur dioxide and volatile acidity",
    caption = "Dataset: UCI Machine Learning Repository"
  )
)
```

### Using *corrplot()*

```{r}
wine.cor <- cor(wine[, 1:11])
corrplot(wine.cor, method = "shade", type = "lower", diag = FALSE, tl.col = "black")
```

Combining with significance test:

```{r}
wine.sig = cor.mtest(wine.cor, conf.level = 0.95)
```

```{r}
corrplot(wine.cor,
         method = "number",
         type = "lower",
         diag = FALSE,
         tl.col = "black",
         tl.srt = 45,
         p.mat = wine.sig$p,
         sig.level = .05)
```

```{r}
corrplot.mixed(wine.cor, 
               lower = "ellipse", 
               upper = "number",
               tl.pos = "lt",
               diag = "l",
               order="AOE",
               tl.col = "black")
```

```{r}
corrplot(wine.cor, 
         method = "ellipse", 
         tl.pos = "lt",
         tl.col = "black",
         order="hclust",
         hclust.method = "ward.D",
         addrect = 3)
```
